# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ex_sim/ex_sim.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ex_sim || ORIG_REF_NAME==ex_sim} -quiet] -quiet

# IP: bd/ex_sim/ip/ex_sim_axi_vip_mst_0/ex_sim_axi_vip_mst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ex_sim_axi_vip_mst_0 || ORIG_REF_NAME==ex_sim_axi_vip_mst_0} -quiet] -quiet

# IP: bd/ex_sim/ip/ex_sim_axi_vip_passthrough_0/ex_sim_axi_vip_passthrough_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ex_sim_axi_vip_passthrough_0 || ORIG_REF_NAME==ex_sim_axi_vip_passthrough_0} -quiet] -quiet

# IP: bd/ex_sim/ip/ex_sim_axi_vip_slv_0/ex_sim_axi_vip_slv_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ex_sim_axi_vip_slv_0 || ORIG_REF_NAME==ex_sim_axi_vip_slv_0} -quiet] -quiet

# XDC: c:/Users/uxli/Documents/Tidalloft/tungsten-grid/ip_project/axi_vip_0_example/axi_vip_0_ex.gen/sources_1/bd/ex_sim/ex_sim_ooc.xdc
