# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/uxli/Documents/Tidalloft/tungsten-grid/ip_project/axi_vip_0_example/axi_vip_0_ex.srcs/sources_1/bd/ex_sim/ip/ex_sim_axi_vip_slv_0/ex_sim_axi_vip_slv_0.xci
# IP: The module: 'ex_sim_axi_vip_slv_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/uxli/Documents/Tidalloft/tungsten-grid/ip_project/axi_vip_0_example/axi_vip_0_ex.gen/sources_1/bd/ex_sim/ip/ex_sim_axi_vip_slv_0/ex_sim_axi_vip_slv_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex_sim_axi_vip_slv_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/uxli/Documents/Tidalloft/tungsten-grid/ip_project/axi_vip_0_example/axi_vip_0_ex.srcs/sources_1/bd/ex_sim/ip/ex_sim_axi_vip_slv_0/ex_sim_axi_vip_slv_0.xci
# IP: The module: 'ex_sim_axi_vip_slv_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/uxli/Documents/Tidalloft/tungsten-grid/ip_project/axi_vip_0_example/axi_vip_0_ex.gen/sources_1/bd/ex_sim/ip/ex_sim_axi_vip_slv_0/ex_sim_axi_vip_slv_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex_sim_axi_vip_slv_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
