-- Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2021.1 (lin64) Build 3247384 Thu Jun 10 19:36:07 MDT 2021
-- Date        : Sun Aug  1 19:46:19 2021
-- Host        : test-ubuntu running 64-bit Ubuntu 20.04.2 LTS
-- Command     : write_vhdl -force -mode funcsim
--               /home/test/Workplace/adi/hdl/projects/m2k/standalone/m2k.gen/sources_1/bd/system/ip/system_axi_rd_wr_combiner_logic_0/system_axi_rd_wr_combiner_logic_0_sim_netlist.vhdl
-- Design      : system_axi_rd_wr_combiner_logic_0
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xc7z010clg225-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;
entity system_axi_rd_wr_combiner_logic_0 is
  port (
    clk : in STD_LOGIC;
    m_axi_awaddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_awlen : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_awcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_awvalid : out STD_LOGIC;
    m_axi_awready : in STD_LOGIC;
    m_axi_wdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_wstrb : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_wready : in STD_LOGIC;
    m_axi_wvalid : out STD_LOGIC;
    m_axi_wlast : out STD_LOGIC;
    m_axi_bvalid : in STD_LOGIC;
    m_axi_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bready : out STD_LOGIC;
    m_axi_arvalid : out STD_LOGIC;
    m_axi_araddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_arlen : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_arready : in STD_LOGIC;
    m_axi_rvalid : in STD_LOGIC;
    m_axi_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_rdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_rlast : in STD_LOGIC;
    m_axi_rready : out STD_LOGIC;
    s_wr_axi_awaddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_wr_axi_awlen : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_wr_axi_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s_wr_axi_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s_wr_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s_wr_axi_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_wr_axi_awvalid : in STD_LOGIC;
    s_wr_axi_awready : out STD_LOGIC;
    s_wr_axi_wdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s_wr_axi_wstrb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s_wr_axi_wready : out STD_LOGIC;
    s_wr_axi_wvalid : in STD_LOGIC;
    s_wr_axi_wlast : in STD_LOGIC;
    s_wr_axi_bvalid : out STD_LOGIC;
    s_wr_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_wr_axi_bready : in STD_LOGIC;
    s_rd_axi_arvalid : in STD_LOGIC;
    s_rd_axi_araddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_rd_axi_arlen : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_rd_axi_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s_rd_axi_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s_rd_axi_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_rd_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s_rd_axi_arready : out STD_LOGIC;
    s_rd_axi_rvalid : out STD_LOGIC;
    s_rd_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_rd_axi_rdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    s_rd_axi_rlast : out STD_LOGIC;
    s_rd_axi_rready : in STD_LOGIC
  );
  attribute NotValidForBitStream : boolean;
  attribute NotValidForBitStream of system_axi_rd_wr_combiner_logic_0 : entity is true;
  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of system_axi_rd_wr_combiner_logic_0 : entity is "system_axi_rd_wr_combiner_logic_0,axi_rd_wr_combiner,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of system_axi_rd_wr_combiner_logic_0 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of system_axi_rd_wr_combiner_logic_0 : entity is "package_project";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of system_axi_rd_wr_combiner_logic_0 : entity is "axi_rd_wr_combiner,Vivado 2021.1";
end system_axi_rd_wr_combiner_logic_0;

architecture STRUCTURE of system_axi_rd_wr_combiner_logic_0 is
  signal \^m_axi_arready\ : STD_LOGIC;
  signal \^m_axi_awready\ : STD_LOGIC;
  signal \^m_axi_bresp\ : STD_LOGIC_VECTOR ( 1 downto 0 );
  signal \^m_axi_bvalid\ : STD_LOGIC;
  signal \^m_axi_rdata\ : STD_LOGIC_VECTOR ( 63 downto 0 );
  signal \^m_axi_rlast\ : STD_LOGIC;
  signal \^m_axi_rresp\ : STD_LOGIC_VECTOR ( 1 downto 0 );
  signal \^m_axi_rvalid\ : STD_LOGIC;
  signal \^m_axi_wready\ : STD_LOGIC;
  signal \^s_rd_axi_araddr\ : STD_LOGIC_VECTOR ( 31 downto 0 );
  signal \^s_rd_axi_arburst\ : STD_LOGIC_VECTOR ( 1 downto 0 );
  signal \^s_rd_axi_arcache\ : STD_LOGIC_VECTOR ( 3 downto 0 );
  signal \^s_rd_axi_arlen\ : STD_LOGIC_VECTOR ( 3 downto 0 );
  signal \^s_rd_axi_arprot\ : STD_LOGIC_VECTOR ( 2 downto 0 );
  signal \^s_rd_axi_arsize\ : STD_LOGIC_VECTOR ( 2 downto 0 );
  signal \^s_rd_axi_arvalid\ : STD_LOGIC;
  signal \^s_rd_axi_rready\ : STD_LOGIC;
  signal \^s_wr_axi_awaddr\ : STD_LOGIC_VECTOR ( 31 downto 0 );
  signal \^s_wr_axi_awburst\ : STD_LOGIC_VECTOR ( 1 downto 0 );
  signal \^s_wr_axi_awcache\ : STD_LOGIC_VECTOR ( 3 downto 0 );
  signal \^s_wr_axi_awlen\ : STD_LOGIC_VECTOR ( 3 downto 0 );
  signal \^s_wr_axi_awprot\ : STD_LOGIC_VECTOR ( 2 downto 0 );
  signal \^s_wr_axi_awsize\ : STD_LOGIC_VECTOR ( 2 downto 0 );
  signal \^s_wr_axi_awvalid\ : STD_LOGIC;
  signal \^s_wr_axi_bready\ : STD_LOGIC;
  signal \^s_wr_axi_wdata\ : STD_LOGIC_VECTOR ( 63 downto 0 );
  signal \^s_wr_axi_wlast\ : STD_LOGIC;
  signal \^s_wr_axi_wstrb\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^s_wr_axi_wvalid\ : STD_LOGIC;
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of clk : signal is "xilinx.com:signal:clock:1.0 clk CLK, xilinx.com:signal:clock:1.0 m_axi_s_wr_axi_s_rd_axi_signal_clock CLK";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of clk : signal is "XIL_INTERFACENAME clk, ASSOCIATED_BUSIF m_axi:s_rd_axi:s_wr_axi, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, INSERT_VIP 0, XIL_INTERFACENAME m_axi_s_wr_axi_s_rd_axi_signal_clock, ASSOCIATED_BUSIF m_axi:s_wr_axi:s_rd_axi, FREQ_HZ 27777778, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN system_sys_ps7_0_FCLK_CLK0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_arready : signal is "xilinx.com:interface:aximm:1.0 m_axi ARREADY";
  attribute X_INTERFACE_INFO of m_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 m_axi ARVALID";
  attribute X_INTERFACE_INFO of m_axi_awready : signal is "xilinx.com:interface:aximm:1.0 m_axi AWREADY";
  attribute X_INTERFACE_INFO of m_axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 m_axi AWVALID";
  attribute X_INTERFACE_INFO of m_axi_bready : signal is "xilinx.com:interface:aximm:1.0 m_axi BREADY";
  attribute X_INTERFACE_INFO of m_axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 m_axi BVALID";
  attribute X_INTERFACE_INFO of m_axi_rlast : signal is "xilinx.com:interface:aximm:1.0 m_axi RLAST";
  attribute X_INTERFACE_INFO of m_axi_rready : signal is "xilinx.com:interface:aximm:1.0 m_axi RREADY";
  attribute X_INTERFACE_PARAMETER of m_axi_rready : signal is "XIL_INTERFACENAME m_axi, DATA_WIDTH 64, PROTOCOL AXI3, FREQ_HZ 27777778, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN system_sys_ps7_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 m_axi RVALID";
  attribute X_INTERFACE_INFO of m_axi_wlast : signal is "xilinx.com:interface:aximm:1.0 m_axi WLAST";
  attribute X_INTERFACE_INFO of m_axi_wready : signal is "xilinx.com:interface:aximm:1.0 m_axi WREADY";
  attribute X_INTERFACE_INFO of m_axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 m_axi WVALID";
  attribute X_INTERFACE_INFO of s_rd_axi_arready : signal is "xilinx.com:interface:aximm:1.0 s_rd_axi ARREADY";
  attribute X_INTERFACE_INFO of s_rd_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 s_rd_axi ARVALID";
  attribute X_INTERFACE_INFO of s_rd_axi_rlast : signal is "xilinx.com:interface:aximm:1.0 s_rd_axi RLAST";
  attribute X_INTERFACE_INFO of s_rd_axi_rready : signal is "xilinx.com:interface:aximm:1.0 s_rd_axi RREADY";
  attribute X_INTERFACE_PARAMETER of s_rd_axi_rready : signal is "XIL_INTERFACENAME s_rd_axi, DATA_WIDTH 64, PROTOCOL AXI3, FREQ_HZ 27777778, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_ONLY, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 0, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN system_sys_ps7_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_rd_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 s_rd_axi RVALID";
  attribute X_INTERFACE_INFO of s_wr_axi_awready : signal is "xilinx.com:interface:aximm:1.0 s_wr_axi AWREADY";
  attribute X_INTERFACE_INFO of s_wr_axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 s_wr_axi AWVALID";
  attribute X_INTERFACE_INFO of s_wr_axi_bready : signal is "xilinx.com:interface:aximm:1.0 s_wr_axi BREADY";
  attribute X_INTERFACE_PARAMETER of s_wr_axi_bready : signal is "XIL_INTERFACENAME s_wr_axi, DATA_WIDTH 64, PROTOCOL AXI3, FREQ_HZ 27777778, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 0, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN system_sys_ps7_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_wr_axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 s_wr_axi BVALID";
  attribute X_INTERFACE_INFO of s_wr_axi_wlast : signal is "xilinx.com:interface:aximm:1.0 s_wr_axi WLAST";
  attribute X_INTERFACE_INFO of s_wr_axi_wready : signal is "xilinx.com:interface:aximm:1.0 s_wr_axi WREADY";
  attribute X_INTERFACE_INFO of s_wr_axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 s_wr_axi WVALID";
  attribute X_INTERFACE_INFO of m_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 m_axi ARADDR";
  attribute X_INTERFACE_INFO of m_axi_arburst : signal is "xilinx.com:interface:aximm:1.0 m_axi ARBURST";
  attribute X_INTERFACE_INFO of m_axi_arcache : signal is "xilinx.com:interface:aximm:1.0 m_axi ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_arlen : signal is "xilinx.com:interface:aximm:1.0 m_axi ARLEN";
  attribute X_INTERFACE_INFO of m_axi_arprot : signal is "xilinx.com:interface:aximm:1.0 m_axi ARPROT";
  attribute X_INTERFACE_INFO of m_axi_arsize : signal is "xilinx.com:interface:aximm:1.0 m_axi ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 m_axi AWADDR";
  attribute X_INTERFACE_INFO of m_axi_awburst : signal is "xilinx.com:interface:aximm:1.0 m_axi AWBURST";
  attribute X_INTERFACE_INFO of m_axi_awcache : signal is "xilinx.com:interface:aximm:1.0 m_axi AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_awlen : signal is "xilinx.com:interface:aximm:1.0 m_axi AWLEN";
  attribute X_INTERFACE_INFO of m_axi_awprot : signal is "xilinx.com:interface:aximm:1.0 m_axi AWPROT";
  attribute X_INTERFACE_INFO of m_axi_awsize : signal is "xilinx.com:interface:aximm:1.0 m_axi AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_bresp : signal is "xilinx.com:interface:aximm:1.0 m_axi BRESP";
  attribute X_INTERFACE_INFO of m_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 m_axi RDATA";
  attribute X_INTERFACE_INFO of m_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 m_axi RRESP";
  attribute X_INTERFACE_INFO of m_axi_wdata : signal is "xilinx.com:interface:aximm:1.0 m_axi WDATA";
  attribute X_INTERFACE_INFO of m_axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 m_axi WSTRB";
  attribute X_INTERFACE_INFO of s_rd_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 s_rd_axi ARADDR";
  attribute X_INTERFACE_INFO of s_rd_axi_arburst : signal is "xilinx.com:interface:aximm:1.0 s_rd_axi ARBURST";
  attribute X_INTERFACE_INFO of s_rd_axi_arcache : signal is "xilinx.com:interface:aximm:1.0 s_rd_axi ARCACHE";
  attribute X_INTERFACE_INFO of s_rd_axi_arlen : signal is "xilinx.com:interface:aximm:1.0 s_rd_axi ARLEN";
  attribute X_INTERFACE_INFO of s_rd_axi_arprot : signal is "xilinx.com:interface:aximm:1.0 s_rd_axi ARPROT";
  attribute X_INTERFACE_INFO of s_rd_axi_arsize : signal is "xilinx.com:interface:aximm:1.0 s_rd_axi ARSIZE";
  attribute X_INTERFACE_INFO of s_rd_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 s_rd_axi RDATA";
  attribute X_INTERFACE_INFO of s_rd_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 s_rd_axi RRESP";
  attribute X_INTERFACE_INFO of s_wr_axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 s_wr_axi AWADDR";
  attribute X_INTERFACE_INFO of s_wr_axi_awburst : signal is "xilinx.com:interface:aximm:1.0 s_wr_axi AWBURST";
  attribute X_INTERFACE_INFO of s_wr_axi_awcache : signal is "xilinx.com:interface:aximm:1.0 s_wr_axi AWCACHE";
  attribute X_INTERFACE_INFO of s_wr_axi_awlen : signal is "xilinx.com:interface:aximm:1.0 s_wr_axi AWLEN";
  attribute X_INTERFACE_INFO of s_wr_axi_awprot : signal is "xilinx.com:interface:aximm:1.0 s_wr_axi AWPROT";
  attribute X_INTERFACE_INFO of s_wr_axi_awsize : signal is "xilinx.com:interface:aximm:1.0 s_wr_axi AWSIZE";
  attribute X_INTERFACE_INFO of s_wr_axi_bresp : signal is "xilinx.com:interface:aximm:1.0 s_wr_axi BRESP";
  attribute X_INTERFACE_INFO of s_wr_axi_wdata : signal is "xilinx.com:interface:aximm:1.0 s_wr_axi WDATA";
  attribute X_INTERFACE_INFO of s_wr_axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 s_wr_axi WSTRB";
begin
  \^m_axi_arready\ <= m_axi_arready;
  \^m_axi_awready\ <= m_axi_awready;
  \^m_axi_bresp\(1 downto 0) <= m_axi_bresp(1 downto 0);
  \^m_axi_bvalid\ <= m_axi_bvalid;
  \^m_axi_rdata\(63 downto 0) <= m_axi_rdata(63 downto 0);
  \^m_axi_rlast\ <= m_axi_rlast;
  \^m_axi_rresp\(1 downto 0) <= m_axi_rresp(1 downto 0);
  \^m_axi_rvalid\ <= m_axi_rvalid;
  \^m_axi_wready\ <= m_axi_wready;
  \^s_rd_axi_araddr\(31 downto 0) <= s_rd_axi_araddr(31 downto 0);
  \^s_rd_axi_arburst\(1 downto 0) <= s_rd_axi_arburst(1 downto 0);
  \^s_rd_axi_arcache\(3 downto 0) <= s_rd_axi_arcache(3 downto 0);
  \^s_rd_axi_arlen\(3 downto 0) <= s_rd_axi_arlen(3 downto 0);
  \^s_rd_axi_arprot\(2 downto 0) <= s_rd_axi_arprot(2 downto 0);
  \^s_rd_axi_arsize\(2 downto 0) <= s_rd_axi_arsize(2 downto 0);
  \^s_rd_axi_arvalid\ <= s_rd_axi_arvalid;
  \^s_rd_axi_rready\ <= s_rd_axi_rready;
  \^s_wr_axi_awaddr\(31 downto 0) <= s_wr_axi_awaddr(31 downto 0);
  \^s_wr_axi_awburst\(1 downto 0) <= s_wr_axi_awburst(1 downto 0);
  \^s_wr_axi_awcache\(3 downto 0) <= s_wr_axi_awcache(3 downto 0);
  \^s_wr_axi_awlen\(3 downto 0) <= s_wr_axi_awlen(3 downto 0);
  \^s_wr_axi_awprot\(2 downto 0) <= s_wr_axi_awprot(2 downto 0);
  \^s_wr_axi_awsize\(2 downto 0) <= s_wr_axi_awsize(2 downto 0);
  \^s_wr_axi_awvalid\ <= s_wr_axi_awvalid;
  \^s_wr_axi_bready\ <= s_wr_axi_bready;
  \^s_wr_axi_wdata\(63 downto 0) <= s_wr_axi_wdata(63 downto 0);
  \^s_wr_axi_wlast\ <= s_wr_axi_wlast;
  \^s_wr_axi_wstrb\(7 downto 0) <= s_wr_axi_wstrb(7 downto 0);
  \^s_wr_axi_wvalid\ <= s_wr_axi_wvalid;
  m_axi_araddr(31 downto 0) <= \^s_rd_axi_araddr\(31 downto 0);
  m_axi_arburst(1 downto 0) <= \^s_rd_axi_arburst\(1 downto 0);
  m_axi_arcache(3 downto 0) <= \^s_rd_axi_arcache\(3 downto 0);
  m_axi_arlen(3 downto 0) <= \^s_rd_axi_arlen\(3 downto 0);
  m_axi_arprot(2 downto 0) <= \^s_rd_axi_arprot\(2 downto 0);
  m_axi_arsize(2 downto 0) <= \^s_rd_axi_arsize\(2 downto 0);
  m_axi_arvalid <= \^s_rd_axi_arvalid\;
  m_axi_awaddr(31 downto 0) <= \^s_wr_axi_awaddr\(31 downto 0);
  m_axi_awburst(1 downto 0) <= \^s_wr_axi_awburst\(1 downto 0);
  m_axi_awcache(3 downto 0) <= \^s_wr_axi_awcache\(3 downto 0);
  m_axi_awlen(3 downto 0) <= \^s_wr_axi_awlen\(3 downto 0);
  m_axi_awprot(2 downto 0) <= \^s_wr_axi_awprot\(2 downto 0);
  m_axi_awsize(2 downto 0) <= \^s_wr_axi_awsize\(2 downto 0);
  m_axi_awvalid <= \^s_wr_axi_awvalid\;
  m_axi_bready <= \^s_wr_axi_bready\;
  m_axi_rready <= \^s_rd_axi_rready\;
  m_axi_wdata(63 downto 0) <= \^s_wr_axi_wdata\(63 downto 0);
  m_axi_wlast <= \^s_wr_axi_wlast\;
  m_axi_wstrb(7 downto 0) <= \^s_wr_axi_wstrb\(7 downto 0);
  m_axi_wvalid <= \^s_wr_axi_wvalid\;
  s_rd_axi_arready <= \^m_axi_arready\;
  s_rd_axi_rdata(63 downto 0) <= \^m_axi_rdata\(63 downto 0);
  s_rd_axi_rlast <= \^m_axi_rlast\;
  s_rd_axi_rresp(1 downto 0) <= \^m_axi_rresp\(1 downto 0);
  s_rd_axi_rvalid <= \^m_axi_rvalid\;
  s_wr_axi_awready <= \^m_axi_awready\;
  s_wr_axi_bresp(1 downto 0) <= \^m_axi_bresp\(1 downto 0);
  s_wr_axi_bvalid <= \^m_axi_bvalid\;
  s_wr_axi_wready <= \^m_axi_wready\;
end STRUCTURE;
